language: scala
scala:
- 2.11.8

env:
  global:
  - LIB_VERSION=$TRAVIS_TAG

deploy:
  skip_cleanup: true
  provider: script
  script: project/publish.sh
  env:
  on:
    tags: true

script: sbt compile
