language: scala
scala:
- 2.11.8

env:
  global:
  - LIB_VERSION=$TRAVIS_BUILD_NUMBER

deploy:
  skip_cleanup: true
  provider: script
  script: project/publish.sh
  on:
    branch: master

script: sbt compile
